FROM golang:1.19.5 as build

LABEL author=yuluo \
    email=yuluo829@aliyun.com \
    version="2023.1.28"

# 为镜像设置必要的环境变量
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /service/ipv6-manager/collect-ipv6-distribution-info-sys

ADD ./apps/collect/collect-ipv6-distribution-info-sys/go.mod .
ADD ./apps/collect/collect-ipv6-distribution-info-sys/go.sum .
RUN go mod download

ADD . .
RUN go build -ldflags="-s -w" -installsuffix cgo -o collectionService ./apps/collect/collect-ipv6-distribution-info-sys/main.go

# 运行：使用scratch作为基础镜像
FROM scratch as prod

# 在build阶段复制时区到
COPY --from=build /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
# 在build阶段复制可执行的go二进制文件app
COPY --from=build /service/ipv6-manager/collect-ipv6-distribution-info-sys/collectionService ./
# 在build阶段复制配置文件
COPY --from=build /service/ipv6-manager/collect-ipv6-distribution-info-sys/conf/config.ini ./apps/collect/collect-ipv6-distribution-info-sys/conf/config.ini

ENTRYPOINT ["/bin/sh", "./collectionService"]
