management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ipv6_manager
      database: ipv6_manager

    redis:
      database: 6
      host: 112.74.111.23
      password: '082916'
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1
          min-idle: 0
